# Generated by Django 3.0.3 on 2020-08-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaccount',
            name='contactNo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usersaccount',
            name='fullName',
            field=models.CharField(max_length=120, verbose_name='Full Name'),
        ),
    ]
