# Generated by Django 3.0.3 on 2020-08-30 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_Custome_Account_Migrations'),
    ]

    operations = [
        # creating the relations between groups and users
        migrations.RunSQL("insert into account_usersaccount_groups"
                          "(usersaccount_id, group_id) values('1', '1')"),
        migrations.RunSQL("insert into account_usersaccount_groups"
                          "(usersaccount_id, group_id) values('2', '2')"),
    ]
