# Generated by Django 3.0.3 on 2020-09-05 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('contactNo', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('review', 'review'), ('accept', 'accept'), ('reject', 'reject')], default='review', max_length=10)),
                ('date_post', models.DateTimeField(auto_now=True, verbose_name='date posted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_images', models.ImageField(blank=True, null=True, upload_to='rooms_photo/')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomsapps.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_status', models.CharField(choices=[('pending', 'pending'), ('accept', 'accept request'), ('reject', 'reject request')], default='pending', max_length=120, null=True)),
                ('date_rent', models.DateTimeField(auto_now=True, null=True, verbose_name='date rent')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomsapps.Rooms')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
